# netlify.toml
[[redirects]]
  from = "/api/*"
  to = "/private/:splat"
  status = 200
  force = true

[build]
  publish = "public"

[context.production.environment]
  NETLIFY_ENVIRONMENT = "production"